Traceback (most recent call last):
  File "train_cnn_with_depth_map.py", line 110, in <module>
    main()
  File "train_cnn_with_depth_map.py", line 107, in main
    train(view)
  File "train_cnn_with_depth_map.py", line 80, in train
    num_ftrs = model.fc.in_features
  File "E:\Programs\miniconda\envs\skeypoint\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'VGG' object has no attribute 'fc'